app/src/main/java/com/example/sid/marwadishaadi/Otp_Verification/Otp_Verification.java
Also, change mobile number with user number and add correct intent to next/submit
=> Update Ot_verification.java // Nirmal

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/sid/marwadishaadi/Chat/AppUtils.java, app/src/main/java/com/example/sid/marwadishaadi/Chat/Author.java, app/src/main/java/com/example/sid/marwadishaadi/Chat/DefaultDialogsActivity.java, app/src/main/java/com/example/sid/marwadishaadi/Chat/DefaultMessagesActivity.java, app/src/main/java/com/example/sid/marwadishaadi/Chat/DemoDialogsActivity.java, app/src/main/java/com/example/sid/marwadishaadi/Chat/DemoMessagesActivity.java, app/src/main/java/com/example/sid/marwadishaadi/Chat/Dialog.java, app/src/main/java/com/example/sid/marwadishaadi/Chat/DialogsFixtures.java, app/src/main/java/com/example/sid/marwadishaadi/Chat/FixturesData.java, app/src/main/java/com/example/sid/marwadishaadi/Chat/Message.java, app/src/main/java/com/example/sid/marwadishaadi/Chat/MessagesFixtures.java, app/src/main/java/com/example/sid/marwadishaadi/Chat/User.java, app/src/main/java/com/example/sid/marwadishaadi/Dashboard.java, app/src/main/java/com/example/sid/marwadishaadi/Otp_Verification/Otp_Verification.java, app/src/main/res/layout/activity_default_dialogs.xml, app/src/main/res/layout/activity_default_messages.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/item_dialog.xml, app/src/main/res/menu/chat_actions_menu.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
Added chat..
removed  style="@style/FacebookLoginButton" from activity_login.xml
=> Added Chat

.idea/modules.xml, app/src/main/java/com/example/sid/marwadishaadi/Search/Search.java, app/src/main/res/drawable/edit_text_border.xml, app/src/main/res/layout/activity_search.xml
1) Made advanced search collapsible.
2) Shifted city field from basic to advanced.
3) Few UI changes to advance search button.
=> Advanced_search and basic search

app/src/main/java/com/example/sid/marwadishaadi/Settings/SettingsActivity.java
#include request
cout<<"Please commit changes";
return 0;
=> Added Logout Option and Intented to Login class

app/src/main/java/com/example/sid/marwadishaadi/MainActivity.java
#include request
cout<<"Please commit changes";
return 0;
=> Added option of login user go to dashboard

app/src/main/java/com/example/sid/marwadishaadi/Dashboard.java
If the user is logged in then on back press at DashBoard then the app will get paused. And go to the main screen(Home).
#include request
cout<<"Please commit changes";
return 0;
=> Added feature of back press

app/src/main/java/com/example/sid/marwadishaadi/Search/Search.java
=> Updated partial search

app/src/main/java/com/example/sid/marwadishaadi/Search/User.java
=> Added boolean checker

app/src/main/java/com/example/sid/marwadishaadi/Search/UsersAdapter.java
=> Updates User Adapter with selection changes

app/build.gradle
compile 'com.amitshekhar.android:android-networking:1.0.0'
Use new build tool 26.0.0 //realesed in just a days
use minSDKVersion 17
=> Added Networking dependencie//  read comment

app/src/main/java/com/example/sid/marwadishaadi/Blocked_Members/BlockAdapter.java
=> Updated BlockAdapter

app/src/main/res/values/strings.xml
Important change is Physical Status
=> Payment Related and some Search related changes

app/src/main/java/com/example/sid/marwadishaadi/Search/BottomSheet.java
=> Added Search Query

app/src/main/java/com/example/sid/marwadishaadi/Chat/DefaultMessagesActivity.java
=> Added block option

app/src/main/java/com/example/sid/marwadishaadi/Blocked_Members/BlockAdapter.java
=> Added Unblock option

app/src/main/java/com/example/sid/marwadishaadi/Blocked_Members/BlockedActivity.java
=> Added list population and add option from chat

app/src/main/java/com/example/sid/marwadishaadi/Membership/MembershipActivity.java
=> Please Update USAP

app/src/main/java/com/example/sid/marwadishaadi/Settings/SettingsActivity.java
=> Updated Setting Block

app/src/main/java/com/example/sid/marwadishaadi/Search/SearchResultsActivity.java
=> Little changes in datasetChanged

app/src/main/java/com/example/sid/marwadishaadi/App.java
=> Added option of Login History Service

app/src/main/java/com/example/sid/marwadishaadi/Chat/DefaultDialogsActivity.java, app/src/main/java/com/example/sid/marwadishaadi/Dashboard_Favourites/FavouritesFragment.java, app/src/main/java/com/example/sid/marwadishaadi/Dashboard_Interest_Received/InterestReceivedFragment.java, app/src/main/java/com/example/sid/marwadishaadi/Dashboard_Interest_Sent/InterestSentFragment.java, app/src/main/java/com/example/sid/marwadishaadi/Dashboard_Recent_Profiles/RecentProfilesFragment.java, app/src/main/java/com/example/sid/marwadishaadi/Dashboard_Reverse_Matching/Reverse_MatchingFragment.java, app/src/main/java/com/example/sid/marwadishaadi/Dashboard_Suggestions/SuggestionsFragment.java, app/src/main/java/com/example/sid/marwadishaadi/Login/LoginActivity.java, app/src/main/java/com/example/sid/marwadishaadi/User_Profile/UserProfileActivity.java, app/src/main/res/layout/activity_user_profile.xml, app/src/main/res/layout/fragment_interest_received.xml, app/src/main/res/layout/fragment_recent__profiles.xml, app/src/main/res/layout/fragment_reverse__matching.xml, app/src/main/res/layout/fragment_suggestions.xml, app/src/main/res/layout/swipe_to_refresh.xml
=> search fixed
